In [7]:
from io import StringIO
import requests
import pandas as pd
import numpy as np
import yfinance as yf

In [ ]:
# URL da página com a lista de empresas do S&P 500
url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"

# Definindo o cabeçalho para a requisição HTTP
headers = {'User-Agent': 'Mozilla/5.0'}

In [ ]:
# Fazendo a requisição HTTP para obter o conteúdo da página
response = requests.get(url, headers=headers)

# Lendo as tabelas da página HTML usando pandas
tables = pd.read_html(StringIO(response.text))

In [ ]:
# Exibindo o número de tabelas encontradas
print(len(tables))   

# Exibindo as primeiras linhas da primeira tabela
tables[0].head()

2

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989

In [27]:
tables[0]['Security'].unique()

<StringArray>
[                    '3M',            'A. O. Smith',    'Abbott Laboratories',
                 'AbbVie',              'Accenture',             'Adobe Inc.',
 'Advanced Micro Devices',        'AES Corporation',                  'Aflac',
   'Agilent Technologies',
 ...
     'Williams Companies',   'Willis Towers Watson',          'Workday, Inc.',
           'Wynn Resorts',            'Xcel Energy',             'Xylem Inc.',
            'Yum! Brands',     'Zebra Technologies',          'Zimmer Biomet',
                 'Zoetis']
Length: 503, dtype: str

In [28]:
tables[0]['Symbol'].unique()

<StringArray>
[ 'MMM',  'AOS',  'ABT', 'ABBV',  'ACN', 'ADBE',  'AMD',  'AES',  'AFL',
    'A',
 ...
  'WMB',  'WTW', 'WDAY', 'WYNN',  'XEL',  'XYL',  'YUM', 'ZBRA',  'ZBH',
  'ZTS']
Length: 503, dtype: str

In [24]:
tables[1]

      vteS&P 500 companies                             vteS&P 500 companies.1
0                   Energy  APA Corporation Baker Hughes Chevron Corporati...
1                Materials  Air Products Albemarle Corporation Amcor Avery...
2              Industrials  3M A. O. Smith Allegion Ametek Automatic Data ...
3   Consumer discretionary  Airbnb Amazon Aptiv AutoZone Best Buy Booking ...
4         Consumer staples  Altria Archer Daniels Midland Brown-Forman Bun...
5              Health Care  Abbott Laboratories AbbVie Agilent Technologie...
6               Financials  Aflac Allstate American Express American Inter...
7   Information technology  Accenture Adobe Inc. Akamai Technologies AMD A...
8   Communication services  Alphabet Inc. AT&T Charter Communications Comc...
9              Real estate  Alexandria Real Estate Equities American Tower...
10               Utilities  AES Corporation Alliant Energy Ameren American...

In [13]:
print(type(tables))

<class 'list'>

In [14]:
# Se for uma lista, verifica o tipo do primeiro item
if isinstance(tables, list) and len(tables) > 0:
    print(type(tables[0]))

<class 'pandas.DataFrame'>