In [1]:
from io import StringIO
import os
import requests
import pandas as pd
import numpy as np
import yfinance as yf

In [2]:
# URL da página com a lista de empresas do S&P 500
url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"

# Definindo o cabeçalho para a requisição HTTP
headers = {'User-Agent': 'Mozilla/5.0'}

In [3]:
# Fazendo a requisição HTTP para obter o conteúdo da página
response = requests.get(url, headers=headers)

# Lendo as tabelas da página HTML usando pandas
tables = pd.read_html(StringIO(response.text))

In [4]:
# Exibindo o número de tabelas encontradas
print(len(tables))   

# Exibindo as primeiras linhas da primeira tabela
tables[0].head()

2

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989

In [5]:
tables[0]['Security'].unique()

<StringArray>
[                    '3M',            'A. O. Smith',    'Abbott Laboratories',
                 'AbbVie',              'Accenture',             'Adobe Inc.',
 'Advanced Micro Devices',        'AES Corporation',                  'Aflac',
   'Agilent Technologies',
 ...
     'Williams Companies',   'Willis Towers Watson',          'Workday, Inc.',
           'Wynn Resorts',            'Xcel Energy',             'Xylem Inc.',
            'Yum! Brands',     'Zebra Technologies',          'Zimmer Biomet',
                 'Zoetis']
Length: 503, dtype: str

In [6]:
tables[0]['Symbol'].unique()

<StringArray>
[ 'MMM',  'AOS',  'ABT', 'ABBV',  'ACN', 'ADBE',  'AMD',  'AES',  'AFL',
    'A',
 ...
  'WMB',  'WTW', 'WDAY', 'WYNN',  'XEL',  'XYL',  'YUM', 'ZBRA',  'ZBH',
  'ZTS']
Length: 503, dtype: str

In [7]:
tables[1]

      vteS&P 500 companies                             vteS&P 500 companies.1
0                   Energy  APA Corporation Baker Hughes Chevron Corporati...
1                Materials  Air Products Albemarle Corporation Amcor Avery...
2              Industrials  3M A. O. Smith Allegion Ametek Automatic Data ...
3   Consumer discretionary  Airbnb Amazon Aptiv AutoZone Best Buy Booking ...
4         Consumer staples  Altria Archer Daniels Midland Brown-Forman Bun...
5              Health Care  Abbott Laboratories AbbVie Agilent Technologie...
6               Financials  Aflac Allstate American Express American Inter...
7   Information technology  Accenture Adobe Inc. Akamai Technologies AMD A...
8   Communication services  Alphabet Inc. AT&T Charter Communications Comc...
9              Real estate  Alexandria Real Estate Equities American Tower...
10               Utilities  AES Corporation Alliant Energy Ameren American...

In [8]:
print(type(tables))

<class 'list'>

In [9]:
# Se for uma lista, verifica o tipo do primeiro item
if isinstance(tables, list) and len(tables) > 0:
    print(type(tables[0]))

<class 'pandas.DataFrame'>

In [10]:
# Transformando as tabelas em DataFrames do pandas
df_constituents = tables[0]
df_changes = tables[1]

In [5]:
# Função para salvar um DataFrame em um arquivo CSV
def save_dataframe(df, file_name):
    base_dir = r"C:\Users\leona\github\stock-markets-analytics-zoomcamp-2026\data"
    file_path = os.path.join(base_dir, f"{file_name}.csv")
    df.to_csv(file_path, index=False)

In [26]:
save_dataframe(df_constituents, "sp500_constituents")

In [27]:
save_dataframe(df_changes, "sp500_changes")

In [11]:
df_constituents

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [12]:
df_constituents.info()

<class 'pandas.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Symbol                 503 non-null    str
 1   Security               503 non-null    str
 2   GICS Sector            503 non-null    str
 3   GICS Sub-Industry      503 non-null    str
 4   Headquarters Location  503 non-null    str
 5   Date added             503 non-null    str
 6   CIK                    503 non-null    int64
 7   Founded                503 non-null    str
dtypes: int64(1), str(7)
memory usage: 31.6 KB

In [13]:
# Convertendo a coluna 'Date added' para datetime
df_constituents['Date added'] = pd.to_datetime(df_constituents['Date added'], errors='coerce')

In [14]:
# Adicionando uma nova coluna com o ano de adição
df_constituents['Year added'] = df_constituents['Date added'].dt.year

---

### Question 1

In [15]:
# Contando o número de ações adicionadas por ano
df_added_per_year = df_constituents.groupby('Year added').size().reset_index(name='Count')
df_added_per_year.head(3)

   Year added  Count
0        1957     52
1        1964      1
2        1965      2

In [16]:
# Encontrando o ano com o maior número de ações adicionadas
df_2020_plus = df_added_per_year[df_added_per_year['Year added'] >= 2020]
df_2020_plus.head(3)

    Year added  Count
51        2020     10
52        2021     10
53        2022     15

In [17]:
year_highest_stokes = df_2020_plus.loc[df_2020_plus['Count'].idxmax()]
year_highest_stokes

Year added    2025
Count           18
Name: 56, dtype: int64

In [18]:
df_over_20_years = df_constituents[df_constituents['Date added'] <= '2006-01-01'].count()
df_over_20_years

Symbol                   218
Security                 218
GICS Sector              218
GICS Sub-Industry        218
Headquarters Location    218
Date added               218
CIK                      218
Founded                  218
Year added               218
dtype: int64

---

### Question 2

In [3]:
# Global Index Tickers
global_index = ['^GSPC', '000001.SS', '^HSI',
                '^AXJO', '^NSEI', '^GSPTSE',
                '^GDAXI', '^FTSE', '^N225',
                '^MXX', '^BVSP']

In [ ]:
# Função para obter dados históricos do S&P 500 usando yfinance
def get_sp500_historical_data(symbol, start_date, end_date):
    """
    Função para obter dados históricos de um símbolo do S&P 500 usando yfinance.
    
    Parâmetros:
    - symbol: Símbolo da ação (string)
    - start_date: Data de início no formato 'YYYY-MM-DD' (string)
    - end_date: Data de término no formato 'YYYY-MM-DD' (string)
    
    Retorna:
    - DataFrame com os dados históricos
    """
    result = {}
    for s in symbol:
        result[s] = yf.download(s, start=start_date, end=end_date, multi_level_index=False)
    
    df = pd.concat(result, names=['Ticker', 'Date']).reset_index()
    return df

In [ ]:
# Obtendo dados históricos do S&P 500 de 1950 até 2026
df_sp500 = get_sp500_historical_data(global_index, '1950-01-01', '2026-08-21')

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

NameError: name 'save_dataframe' is not defined

In [ ]:
# Salvando o DataFrame com os dados históricos do S&P 500 em um arquivo CSV
save_dataframe(df_sp500, "global_sp500")

In [ ]:
# Função para calcular o crescimento ano a ano (YTD) para cada ticker
def get_prices(df, date):
    
    df = df[df['Date'] > date]
    # Pivot the DataFrame to have dates as index and tickers as columns
    close_prices = df.pivot(index= 'Date', columns='Ticker', values='Close')
    # Calculating the first and last prices for each ticker
    first_price = close_prices.bfill().iloc[0]
    last_price = close_prices.ffill().iloc[-1]
    # Calculating the year-to-date growth for each ticker
    growing = (last_price / first_price - 1) * 100
    return growing

In [ ]:
# Function to compare the growth of each ticker against the S&P 500
def compare_growth(df):
    index_max_growth = df > df.loc['^GSPC']
    return index_max_growth

In [ ]:
# Calculando o crescimento para diferentes períodos
df_prices_2026 = get_prices(df_sp500, '2026-01-01')
df_prices_2023 = get_prices(df_sp500, '2023-01-01')
df_prices_2021 = get_prices(df_sp500, '2021-01-01')
df_prices_2016 = get_prices(df_sp500, '2016-01-01')

In [ ]:
# Comparando o crescimento dos tickers em relação ao S&P 500
compare_ytd = compare_growth(df_prices_2026)
compare_ytd

Ticker
000001.SS    False
^AXJO        False
^BVSP        False
^FTSE        False
^GDAXI       False
^GSPC        False
^GSPTSE       True
^HSI         False
^MXX         False
^N225         True
^NSEI        False
dtype: bool

In [25]:
compare_10_years = compare_growth(df_prices_2016)
compare_10_years

Ticker
000001.SS    False
^AXJO        False
^BVSP         True
^FTSE        False
^GDAXI       False
^GSPC        False
^GSPTSE      False
^HSI         False
^MXX         False
^N225        False
^NSEI        False
dtype: bool

In [24]:
compare_5_years = compare_growth(df_prices_2021)
compare_5_years

Ticker
000001.SS    False
^AXJO        False
^BVSP        False
^FTSE        False
^GDAXI       False
^GSPC        False
^GSPTSE       True
^HSI         False
^MXX         False
^N225         True
^NSEI        False
dtype: bool

In [23]:
compare_3_years = compare_growth(df_prices_2023)
compare_3_years

Ticker
000001.SS    False
^AXJO        False
^BVSP        False
^FTSE        False
^GDAXI       False
^GSPC        False
^GSPTSE      False
^HSI         False
^MXX         False
^N225         True
^NSEI        False
dtype: bool

In [ ]:
# Summarizing the results
print("YTD:", compare_ytd.sum())
print("10 anos:", compare_10_years.sum())
print("5 anos:", compare_5_years.sum())
print("3 anos:", compare_3_years.sum())

YTD: 2
10 anos: 1
5 anos: 2
3 anos: 1

---

### Question 3

In [ ]:
# Obtendo dados históricos do S&P 500
df_historical_sp500 = df_sp500[df_sp500['Ticker'] == '^GSPC']
df_historical_sp500 = df_historical_sp500[['Date', 'Close']].reset_index(drop=True)
df_historical_sp500

            Date        Close
0     1950-01-03    16.660000
1     1950-01-04    16.850000
2     1950-01-05    16.930000
3     1950-01-06    16.980000
4     1950-01-09    17.080000
...          ...          ...
19275 2026-08-14  7785.759766
19276 2026-08-17  7745.060059
19277 2026-08-18  7691.759766
19278 2026-08-19  7707.979980
19279 2026-08-20  7641.160156

[19280 rows x 2 columns]

In [ ]:
# Calculando o valor máximo acumulado do S&P 500
df_historical_sp500['cummax'] = df_historical_sp500['Close'].cummax()

In [ ]:
# Identificando se o preço de fechamento é um novo recorde histórico
df_historical_sp500['is_ath'] = df_historical_sp500['Close'] == df_historical_sp500['cummax']

In [ ]:
# Obtendo os dias em que o S&P 500 atingiu um novo recorde histórico
historical_max_days = df_historical_sp500[df_historical_sp500['is_ath']]
historical_max_days[['Date', 'Close']]

            Date        Close
0     1950-01-03    16.660000
1     1950-01-04    16.850000
2     1950-01-05    16.930000
3     1950-01-06    16.980000
4     1950-01-09    17.080000
...          ...          ...
19223 2026-06-01  7599.959961
19224 2026-06-02  7609.779785
19267 2026-08-04  7736.520020
19270 2026-08-07  7757.640137
19274 2026-08-13  7798.990234

[1537 rows x 2 columns]